### ISSUE TITLE
Support the latest support libs (27.1.0+)

### ISSUE THREAD

**Issue by cpoppema** [cpoppema/pass-mobile-android#1]
While updating dependencies, including the support libs, I ran into the following issue. Since 27.1.0 - in [no particular major update](https://android.googlesource.com/platform/frameworks/support/+/c39d9c75590eca86a5e7e32a8824ba04a0d42e9b%5E%21/#F234) - access is restricted to ListViewCompat (the class still exists). Either a replacement or similar ListView implementation, or a copy (for now) would do to update past 27.0.2. If this cannot be done, looking into replacing existing behavior is necessary.

When replacing it with `android.widget.ListView`, an exception[1] will occur when triggering[ this line](https://github.com/cpoppema/pass-mobile-android/blob/204d3f1b9205a0860c105a18bcbb5ca3985cab2f/app/src/main/java/mobile/android/pass/secrets/SecretsActivity.java#L490):

```
mListView.onRestoreInstanceState(mListViewState);
```

Without manually managing mListViewState it runs without errors, but e.g. scrolling position is lost when resuming/restoring.

[1]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelableandroid.widget.AbsListView$SavedState.getSuperState()' on a null object reference
  at android.widget.AbsListView.onRestoreInstanceState(AbsListView.java:1891)
  at mobile.android.pass.secrets.SecretsActivity$4.run(SecretsActivity.java:518)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6541)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by cpoppema** [comment]
Finally got it done. See https://github.com/cpoppema/pass-mobile-android/commit/fa1222f24782f1973970e23f8b148cee6831843e which will be part of the new update after some more testing.

Update also contains:
- Updated support libs and fixing deprecation warnings here and there, but in the end actually replacing it with [androidx](https://developer.android.com/jetpack/androidx).
- As mentioned above, workarounds to deal with the fact ListViewCompat can no longer be used.
- Small bugfix: opening PopupMenu + dismissing it and doing orientation change would actually show it again.
- One deprecation was [ProgressDialog](https://developer.android.com/reference/android/app/ProgressDialog.html). This has been replaced with a ProgressBar. It mostly looks the same, it's just no longer a simple dialog that can be dismissed to cancel an action. It now has an explicit cancel button below the progress bar (still a circular one).
- Some fixed deprecation warnings seem temporary, ie. Loaders have been replaced with [ViewModels](https://developer.android.com/topic/libraries/architecture/viewmodel#loaders). (new support lib in androidx), so that needs to be refactored. One day.
- Minor quality of life improvement: search bar trims input. This is especially useful after using the auto-suggest on the keyboard which automatically adds a space, matching nothing.
